version: '3'
services:
  redis:
    container_name: fin_redis
    image: redislabs/redistimeseries
    ports:
      - "6379:6379"
    volumes:
      - $PWD/data_assets/redis:/data_assets
  mysql:
    container_name: fin_mysql
    image: mysql
    ports:
     - "3306:3306"
    environment:
       - MYSQL_ROOT_PASSWORD=mysql
       - MYSQL_DATABASE=findb
    volumes:
       - $PWD/data_assets/mysql/data:/var/lib/mysql
       - $PWD/data_assets/mysql/init:/docker-entrypoint-initdb.d/:ro
  algo:
    container_name: fin_algo
    build: .
    depends_on:
       - mysql
       - redis
    environment:
      - MYSQL_URL=fin_mysql
      - REDIS_URL=fin_redis
    ports:
      - "5000:5000"

networks:
  default:
    name: fin-net