version: '3'
services:
  redis:
    container_name: fin_redis
    image: redislabs/redistimeseries
    ports:
      - "6379:6379"
    volumes:
      - $PWD/data/redis:/data
#      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
  mysql:
    container_name: fin_mysql
    image: mysql
    ports:
     - "3306:3306"
    environment:
       - MYSQL_ROOT_PASSWORD=mysql
       - MYSQL_DATABASE=findb
    volumes:
       - $PWD/data/mysql/data:/var/lib/mysql
       - $PWD/data/mysql/init:/docker-entrypoint-initdb.d/:ro